version: '3'

services:
  pgsql_db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SlowTestData

  slowdash:
    image: slowdash
    volumes:
      - .:/project
    ports:
      - "18881:18881"
    environment:
      - DB_URL=postgresql://postgres:postgres@pgsql_db:5432/SlowTestData

  testdata:
    image: slowdash
    command: python /slowdash/system/client/slowpy/test/generate-testdata.py --db-url=postgresql://postgres:postgres@pgsql_db:5432/SlowTestData
