version: '3'

services:
  slowdash:
    image: slowdash
    volumes:
      - .:/project
    ports:
      - "18881:18881"

  testdata:
    image: slowdash
    volumes:
      - .:/project
    command: python /project/generate-testdata.py --db-url=sqlite:///SlowTestData
