version: '3'

services:
  slowdash:
    image: slowdash
    ports:
      - "18881:18881"
    environment:
      - SLOWDASH_INIT_DATASOURCE_URL=postgresql://postgres:postgres@pgsql_db:5432/SlowTestData
      - SLOWDASH_INIT_TIMESERIES_SCHEMA=slowpy_ts[channel]@timestamp(unix)=value

  pgsql_db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SlowTestData

  testdata:
    image: slowdash
    command: python /slowdash/ExampleProjects/Test_PostgreSQL/generate-testdata.py --db-url=postgresql://postgres:postgres@pgsql_db:5432/SlowTestData
