version: '3'

services:
  pgsql_db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SlowTestData

  slowdash:
    image: slowdash
    ports:
      - "18881:18881"
    environment:
      - SLOWDASH_INIT_DATASOURCE_URL=postgresql://postgres:postgres@pgsql_db:5432/SlowTestData
      - SLOWDASH_INIT_TIMESERIES_SCHEMA=ts_data[channel]@timestamp(unix)=value

  testdata:
    image: slowdash
    command: python /slowdash/system/client/slowpy/test/generate-testdata.py --db-url=postgresql://postgres:postgres@pgsql_db:5432/SlowTestData
