version: '3'

services:

  rabbit-broker:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=dripline
      - RABBITMQ_DEFAULT_PASS=dripline

  postgres:
    image: postgres:16.0
    volumes:
      - ./postgres_init.d:/docker-entrypoint-initdb.d
    environment:
      # per the docs, you do *not* want to run with this configuration in production
      - POSTGRES_HOST_AUTH_METHOD=trust

  key-value-store:
    image: driplineorg/dripline-python:v4.5.8
    depends_on:
      - rabbit-broker
    volumes:
      - ./authentications.json:/root/authentications.json
      - ./key-value-store.yaml:/root/key-value-store.yaml
    command:
      - dl-serve
      - -c
      - /root/key-value-store.yaml

  sensor-logger:
    image: driplineorg/dripline-python:v4.5.8
    depends_on:
      - rabbit-broker
      - postgres
    volumes:
      - ./authentications.json:/root/authentications.json
      - ./sensor-logger.yaml:/root/sensor-logger.yaml
    command:
      - dl-serve
      - -c
      - /root/sensor-logger.yaml

  slowdash:
    image: slowdash-dripline
    depends_on:
      - rabbit-broker
      - postgres
    ports:
      - "18881:18881"
    volumes:
      - ./authentications.json:/home/slowuser/authentications.json
      - ./slowdash.d:/project
