name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build SlowDash Docker image
        run: docker build -t ghcr.io/slowproj/slowdash:latest .
          
      - name: Build SlowPy-Notebook Docker image
        run: docker build -f ./lib/Dockerfile -t ghcr.io/slowproj/slowpy-notebook:latest ./lib
          
      - name: Push SlowDash Docker image to GitHub Container Registry
        run: docker push ghcr.io/slowproj/slowdash:latest

      - name: Push SlowPy-Notebook Docker image to GitHub Container Registry
        run: docker push ghcr.io/slowproj/slowpy-notebook:latest
