name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build Docker image
        run: docker build -t slowproj/slowdash:latest .
        run: docker build -f ./lib/Dockerfile -t slowproj/slowpy-notebook:latest ./lib

      - name: Push Docker image to DockerHub
        run: docker push slowproj/slowdash:latest
        run: docker push slowproj/slowpy-notebook:latest
